version: "3.8"

services:
    app-db:
        image: mongo:latest
        restart: unless-stopped
        ports:
            - "27017:27017"
        expose:
            - "27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=todoapp

    todo-service:
        build: ./todo-service
        ports:
            - "3000:3000"
        container_name: todo-service-app
        restart: unless-stopped
        depends_on:
            - app-db
        environment:
            - MONGO_HOST=app-db
            - MONGO_PORT=27017
            - MONGODB_URI=mongodb://admin:admin@app-db:27017/?authSource=admin

    auth-service:
        build: ./auth-service
        deploy:
            replicas: 2
        restart: unless-stopped
        depends_on:
            - app-db
        environment:
            - MONGODB_URI=mongodb://admin:admin@app-db:27017/?authSource=admin
    
    auth-proxy:
        image: nginx:latest
        volumes:
            - ./auth-service/conf.d:/etc/nginx/conf.d
        depends_on:
            - auth-service
        ports:
            - "3002:3000"